export const GET_BOOKS_REQUEST="GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS="GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE="GET_BOOKS_FAILURE";


export const EDIT_BOOKS_REQUEST="EDIT_BOOKS_REQUEST";
export const EDIT_BOOKS_SUCCESS="EDIT_BOOKS_SUCCESS";
export const EDIT_BOOKS_FAILURE="EDIT_BOOKS_FAILURE";


export const DELETE_BOOKS_REQUEST="DELETE_BOOKS_REQUEST";
export const DELETE_BOOKS_SUCCESS="DELETE_BOOKS_SUCCESS";
export const DELETE_BOOKS_FAILURE="DELETE_BOOKS_FAILURE";



export const POST_BOOKS_REQUEST="POST_BOOKS_REQUEST";
export const POST_BOOKS_SUCCESS="POST_BOOKS_SUCCESS";
export const POST_BOOKS_FAILURE="POST_BOOKS_FAILURE";